export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const PRODUCT_LOADED = "PRODUCT_LOADED";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const REMOVE_PRODUCT = "REMOVE_PRODUCT";
export const LOAD_PRODUCTS = "LOAD_PRODUCTS";
export const ADD_PRODUCTS = "ADD_PRODUCTS";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";

// for filter
export const TOGGLE_BRANDS = "TOGGLE_BRANDS";
export const TOGGLE_STOCK = "TOGGLE_STOCK";
export const SEARCH_PRODUCT = "SEARCH_PRODUCT";
export const REMOVE_STOCK = "REMOVE_STOCK";
export const REMOVE_BRANDS = "REMOVE_BRANDS";
